# Use the official NGINX image with Alpine Linux as the base image
FROM nginx:alpine

# Copy the contents of the 'public' directory into the NGINX html directory
COPY public /usr/share/nginx/html

# Expose port 80 to allow incoming traffic to the web server
EXPOSE 80
